#Constants
{{$NODES_PER_NAMESPACE := MinInt .Nodes (DefaultParam .NODES_PER_NAMESPACE 1)}}
{{$CL2_WORKLOAD_PER_NAMESPACE := DefaultParam .CL2_WORKLOAD_PER_NAMESPACE 1}}
{{$CL2_PODS_PER_WORKLOAD := DefaultParam .CL2_PODS_PER_WORKLOAD 10}}
{{$CL2_TUNINGSET_QPS := DefaultParam .CL2_TUNINGSET_QPS 5}}
{{$CL2_LISTPODS_PER_WORKLOAD := DefaultParam .CL2_LISTPODS_PER_WORKLOAD 1}}
{{$LISTPODS_Interval := DefaultParam .LISTPODS_Interval 5}}
{{$MAX_GET_PODS_COUNT := DefaultParam .MAX_GET_PODS_COUNT 5}}
{{$DENSITY_TEST_THROUGHPUT := DefaultParam .DENSITY_TEST_THROUGHPUT 5}}
{{$SCHEDULER_THROUGHPUT_THRESHOLD := DefaultParam .CL2_SCHEDULER_THROUGHPUT_THRESHOLD 0}}
{{$LATENCY_POD_CPU := DefaultParam .LATENCY_POD_CPU 0.01}}
{{$LATENCY_POD_MEMORY := DefaultParam .LATENCY_POD_MEMORY 0.03}}
{{$KUBEMARK_HOLLOW_NODE_CPU := DefaultParam .LATENCY_POD_CPU 10}}
{{$KUBEMARK_HOLLOW_NODE_MEMORY := DefaultParam .LATENCY_POD_MEMORY 30}}
{{$MIN_LATENCY_PODS := 3}}
{{$MIN_SATURATION_PODS_TIMEOUT := 60}}
{{$CL2_ENABLE_KUBEMARK := DefaultParam .CL2_ENABLE_KUBEMARK false}}
{{$CL2_KUBEMARK_NODE_COUNT:= DefaultParam .CL2_KUBEMARK_NODE_COUNT 1}}
{{$USE_SIMPLE_LATENCY_QUERY := DefaultParam .USE_SIMPLE_LATENCY_QUERY false}}
{{$WARM_UP_CLUSTER := DefaultParam .WARM_UP_CLUSTER false}}
{{$ENABLE_RESTART_COUNT_CHECK := DefaultParam .ENABçLE_RESTART_COUNT_CHECK true}}
{{$RESTART_COUNT_THRESHOLD_OVERRIDES:= DefaultParam .RESTART_COUNT_THRESHOLD_OVERRIDES ""}}
#Variables
{{$namespaces := DivideInt .Nodes $NODES_PER_NAMESPACE}}
{{$warmUpNamespaces := DivideInt $namespaces 10}}
{{$warmPodsPerNamespace := 10}}

{{$kubemarkReplicationControllerSpec := DefaultParam .KUBEMARK_ReplicationController_SPEC "kubemark-rc.yaml"}}
{{$listpodsDeploymentSpec := DefaultParam .LISTPODS_DEPLOYMENT_SPEC "podslister-deployment.yaml"}}
{{$latencyDeploymentSpec := DefaultParam .LATENCY_DEPLOYMENT_SPEC "deployment.yaml"}}
{{$API_AVAILABILITY_PERCENTAGE_THRESHOLD := DefaultParam .CL2_API_AVAILABILITY_PERCENTAGE_THRESHOLD 99.5}}
{{$CUSTOM_ALLOWED_CONTAINER_RESTARTS := DefaultParam .CL2_CUSTOM_ALLOWED_CONTAINER_RESTARTS ""}}



name: kube-apiserver
namespace:
  number: {{$namespaces}}
tuningSets:
- name: Uniform5qps
  qpsLoad:
    qps: {{$CL2_TUNINGSET_QPS}}
steps:
{{if $WARM_UP_CLUSTER}}
- name: Starting warming up pod measurements
  measurements:
  - Identifier: WaitForRunningWarnUpDeployments
    Method: WaitForControlledPodsRunning
    Params:
      action: start
      apiVersion: apps/v1
      kind: Deployment
      labelSelector: group = warmup
      operationTimeout: 15m

- name: Creating warming up pods
  phases:
  - namespaceRange:
      min: 1
      max: {{$warmUpNamespaces}}
    replicasPerNamespace: 1
    tuningSet: Uniform5qps
    objectBundle:
    - basename: warmup-deployment
      objectTemplatePath: {{$latencyDeploymentSpec}}
      templateFillMap:
        Replicas: {{$warmPodsPerNamespace}}
        Group: latency
        CpuRequest: {{$LATENCY_POD_CPU}}m
        MemoryRequest: {{$LATENCY_POD_MEMORY}}M
{{end}}

- name: Starting measurements
  measurements:
  - Identifier: APIResponsivenessPrometheus
    Method: APIResponsivenessPrometheus
    Params:
      action: start
  - Identifier: APIResponsivenessPrometheusSimple
    Method: APIResponsivenessPrometheus
    Params:
      action: start
  - Identifier: APIAvailability
    Method: APIAvailability
    Params:
      action: start
      pollFrequency: "3s"
      hostPollTimeoutSeconds: 5
      threshold: {{$API_AVAILABILITY_PERCENTAGE_THRESHOLD}}
  - Identifier: ContainerRestarts
    Method: ContainerRestarts
    Params:
      action: start
      container: kube-apiserver
      enableViolations: true
      defaultAllowedRestarts: 1
      customAllowedRestarts: {{YamlQuote $CUSTOM_ALLOWED_CONTAINER_RESTARTS 4}}
  - Identifier: ContainerCPU
    Method: GenericPrometheusQuery
    Params:
      action: start
      metricName: ContainerCPU
      metricVersion: v1
      unit: cores
      dimensions:
        - container
      queries:
        - name: max
          query: max_over_time(rate(container_cpu_usage_seconds_total{container="kube-apiserver",endpoint="kubelet"}[1m])[%v:])
          requireSamples: true
        - name: Perc99
          query: quantile_over_time(0.99, (rate(container_cpu_usage_seconds_total{container="kube-apiserver",endpoint="kubelet"}[1m]))[%v:])
          requireSamples: true
        - name: Perc90
          query: quantile_over_time(0.90, (rate(container_cpu_usage_seconds_total{container="kube-apiserver",endpoint="kubelet"}[1m]))[%v:])
          requireSamples: true
        - name: Perc50
          query: quantile_over_time(0.50, (rate(container_cpu_usage_seconds_total{container="kube-apiserver",endpoint="kubelet"}[1m]))[%v:])
          requireSamples: true
  - Identifier: ContainerMemory
    Method: GenericPrometheusQuery
    Params:
      action: start
      metricName: ContainerMemory
      metricVersion: v1
      unit: MiB
      dimensions:
        - container
      queries:
        - name: max
          query: max_over_time((container_memory_working_set_bytes{container="kube-apiserver",endpoint="kubelet"} / 1024 / 1024)[%v:])
          requireSamples: true
        - name: Perc99
          query: quantile_over_time(0.99, (container_memory_working_set_bytes{container="kube-apiserver",endpoint="kubelet"} / 1024 / 1024)[%v:])
          requireSamples: true
        - name: Perc90
          query: quantile_over_time(0.90, (container_memory_working_set_bytes{container="kube-apiserver",endpoint="kubelet"} / 1024 / 1024)[%v:])
          requireSamples: true
        - name: Perc50
          query: quantile_over_time(0.50, (container_memory_working_set_bytes{container="kube-apiserver",endpoint="kubelet"} / 1024 / 1024)[%v:])
          requireSamples: true

- name: Starting list/get pod measurements
  measurements:
    - Identifier: WaitForRunningListpodsDeployments
      Method: WaitForControlledPodsRunning
      Params:
        action: start
        apiVersion: apps/v1
        kind: Deployment
        labelSelector: group = listpods
        operationTimeout: 15m

- name: Creating list/get pods
  phases:
    - namespaceRange:
        min: 1
        max: {{$namespaces}}
      replicasPerNamespace: {{$CL2_TUNINGSET_QPS}}
      tuningSet: Uniform5qps
      objectBundle:
        - basename: listpods-deployment
          objectTemplatePath: {{$listpodsDeploymentSpec}}
          templateFillMap:
            Replicas: {{$CL2_LISTPODS_PER_WORKLOAD}}
            Group: listpods
            CpuRequest: 1m
            MemoryRequest: 10M
            MaxPodsCount: {{$MAX_GET_PODS_COUNT}}
            ListInterval: {{$LISTPODS_Interval}}

- name: Waiting for list/get pods to be running
  measurements:
    - Identifier: WaitForRunningListpodsDeployments
      Method: WaitForControlledPodsRunning
      Params:
        action: gather

#- name: Starting latency pod measurements
#  measurements:
#  - Identifier: PodStartupLatency
#    Method: PodStartupLatency
#    Params:
#      action: start
#      labelSelector: group = latency
#  - Identifier: WaitForRunningLatencyDeployments
#    Method: WaitForControlledPodsRunning
#    Params:
#      action: start
#      apiVersion: apps/v1
#      kind: Deployment
#      labelSelector: group = latency
#      operationTimeout: 15m

- name: Creating latency pods
  phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: {{$CL2_WORKLOAD_PER_NAMESPACE}}
    tuningSet: Uniform5qps
    objectBundle:
    - basename: latency-deployment
      objectTemplatePath: {{$latencyDeploymentSpec}}
      templateFillMap:
        Replicas: {{$CL2_PODS_PER_WORKLOAD}}
        Group: latency
        CpuRequest: {{$LATENCY_POD_CPU}}m
        MemoryRequest: {{$LATENCY_POD_MEMORY}}M

#- name: Waiting for latency pods to be running
#  measurements:
#  - Identifier: WaitForRunningLatencyDeployments
#    Method: WaitForControlledPodsRunning
#    Params:
#      action: gather

- name: Deleting latency pods
  phases:
  - namespaceRange:
      min: 1
      max: {{$namespaces}}
    replicasPerNamespace: 0
    tuningSet: Uniform5qps
    objectBundle:
    - basename: latency-deployment
      objectTemplatePath: {{$latencyDeploymentSpec}}

#- name: Waiting for latency pods to be deleted
#  measurements:
#  - Identifier: WaitForRunningLatencyDeployments
#    Method: WaitForControlledPodsRunning
#    Params:
#      action: gather

#- name: Collecting pod startup latency
#  measurements:
#  - Identifier: PodStartupLatency
#    Method: PodStartupLatency
#    Params:
#      action: gather

- name: Deleting list/get pods
  phases:
    - namespaceRange:
        min: 1
        max: {{$namespaces}}
      replicasPerNamespace: 0
      tuningSet: Uniform5qps
      objectBundle:
        - basename: listpods-deployment
          objectTemplatePath: {{$listpodsDeploymentSpec}}

- name: Waiting for list/get pods to be deleted
  measurements:
    - Identifier: WaitForRunningListpodsDeployments
      Method: WaitForControlledPodsRunning
      Params:
        action: gather

{{if $WARM_UP_CLUSTER}}
- name: Deleting warming up pods
  phases:
    - namespaceRange:
        min: 1
        max: {{$warmUpNamespaces}}
      replicasPerNamespace: 0
      tuningSet: Uniform5qps
      objectBundle:
        - basename: warmup-deployment
          objectTemplatePath: {{$latencyDeploymentSpec}}
{{end}}

- name: Collecting measurements
  measurements:
  - Identifier: APIResponsivenessPrometheusSimple
    Method: APIResponsivenessPrometheus
    Params:
      action: gather
      enableViolations: true
      useSimpleLatencyQuery: true
      summaryName: APIResponsivenessPrometheus_simple
  {{if not $USE_SIMPLE_LATENCY_QUERY}}
  - Identifier: APIResponsivenessPrometheus
    Method: APIResponsivenessPrometheus
    Params:
      action: gather
  {{end}}
  - Identifier: APIAvailability
    Method: APIAvailability
    Params:
      action: gather
      pollFrequency: "3s"
      hostPollTimeoutSeconds: 3
      threshold: {{$API_AVAILABILITY_PERCENTAGE_THRESHOLD}}
  - Identifier: ContainerRestarts
    Method: ContainerRestarts
    Params:
      action: gather
      container: kube-apiserver
      enableViolations: true
      defaultAllowedRestarts: 1
      customAllowedRestarts: {{YamlQuote $CUSTOM_ALLOWED_CONTAINER_RESTARTS 4}}
  - Identifier: ContainerCPU
    Method: GenericPrometheusQuery
    Params:
      action: gather
      enableViolations: true
      metricName: ContainerCPU
      metricVersion: v1
      unit: cores
      dimensions:
        - container
      queries:
        - name: max
          query: max_over_time(rate(container_cpu_usage_seconds_total{container="kube-apiserver",endpoint="kubelet"}[1m])[%v:])
          requireSamples: true
        - name: Perc99
          query: quantile_over_time(0.99, (rate(container_cpu_usage_seconds_total{container="kube-apiserver",endpoint="kubelet"}[1m]))[%v:])
          requireSamples: true
        - name: Perc90
          query: quantile_over_time(0.90, (rate(container_cpu_usage_seconds_total{container="kube-apiserver",endpoint="kubelet"}[1m]))[%v:])
          requireSamples: true
        - name: Perc50
          query: quantile_over_time(0.50, (rate(container_cpu_usage_seconds_total{container="kube-apiserver",endpoint="kubelet"}[1m]))[%v:])
          requireSamples: true
  - Identifier: ContainerMemory
    Method: GenericPrometheusQuery
    Params:
      action: gather
      enableViolations: true
      metricName: ContainerMemory
      metricVersion: v1
      unit: MiB
      dimensions:
        - container
      queries:
        - name: max
          query: max_over_time((container_memory_working_set_bytes{container="kube-apiserver",endpoint="kubelet"} / 1024 / 1024)[%v:])
          requireSamples: true
        - name: Perc99
          query: quantile_over_time(0.99, (container_memory_working_set_bytes{container="kube-apiserver",endpoint="kubelet"} / 1024 / 1024)[%v:])
          requireSamples: true
        - name: Perc90
          query: quantile_over_time(0.90, (container_memory_working_set_bytes{container="kube-apiserver",endpoint="kubelet"} / 1024 / 1024)[%v:])
          requireSamples: true
        - name: Perc50
          query: quantile_over_time(0.50, (container_memory_working_set_bytes{container="kube-apiserver",endpoint="kubelet"} / 1024 / 1024)[%v:])
          requireSamples: true
