# To mitigate https://github.com/kubernetes/kubernetes/issues/96635 we have to delete
# configmaps and secrets only AFTER the pods using that configmap/secret are deleted.
# TODO(mborsz): Merge this back to reconcile-objects.yaml once the issue above is fixed.

  {{$actionName := printf "%s objects" .actionName}}
  {{$namespaces := .namespaces}}
  {{$tuningSet := .tuningSet}}
  
  {{$deploymentsPerNamespace := .deploymentsPerNamespace}}

steps:
  - name: {{$actionName}} configmaps and secrets
    phases:
      - namespaceRange:
          min: 1
          max: {{$namespaces}}
        replicasPerNamespace: {{$deploymentsPerNamespace}}
        tuningSet: {{$tuningSet}}
        objectBundle:
          - basename: deployment
            objectTemplatePath: configmap.yaml
          - basename: deployment
            objectTemplatePath: secret.yaml
