apiVersion: v1
kind: ReplicationController
metadata:
  name: hollow-node
  namespace: kubemark
spec:
  replicas: 10
  selector:
    kubemark: hollow-node
  template:
    metadata:
      labels:
        kubemark: hollow-node
    spec:
      initContainers:
        - name: init-inotify-limit
          image: docker.io/busybox:latest
          command: ['sysctl', '-w', 'fs.inotify.max_user_instances=200']
          securityContext:
            privileged: true
      volumes:
        - name: kubeconfig-volume
          secret:
            secretName: kubeconfig
        - name: logs-volume
          hostPath:
            path: /var/log
      containers:
        - name: hollow-kubelet
          image: maclonma/kubemark:v1.20
          ports:
            - containerPort: 4194
            - containerPort: 10250
            - containerPort: 10255
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command:
            - /kubemark
          args:
            - --morph=kubelet
            - --name=$(NODE_NAME)
            - --kubeconfig=/kubeconfig/kubelet.kubeconfig
            - --alsologtostderr
            - --v=2
            - --node-labels=kubemark=hollow-node
          volumeMounts:
            - name: kubeconfig-volume
              mountPath: /kubeconfig
              readOnly: true
            - name: logs-volume
              mountPath: /var/log
          resources:
            requests:
              cpu: 20m
              memory: 50M
            limits:
              cpu: 20m
              memory: 50M
          securityContext:
            privileged: true
        - name: hollow-proxy
          image: maclonma/kubemark:v1.20
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command:
            - /kubemark
          args:
            - --morph=proxy
            - --name=$(NODE_NAME)
            - --use-real-proxier=false
            - --kubeconfig=/kubeconfig/kubeproxy.kubeconfig
            - --alsologtostderr
            - --v=2
            - --node-labels=kubemark=hollow-node
          volumeMounts:
            - name: kubeconfig-volume
              mountPath: /kubeconfig
              readOnly: true
            - name: logs-volume
              mountPath: /var/log
          resources:
            requests:
              cpu: 20m
              memory: 50M
            limits:
              cpu: 20m
              memory: 50M
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubemark
                operator: DoesNotExist
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists