apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
       feature: exec
  template:
    metadata:
       labels:
         feature: exec
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubemark
                    operator: DoesNotExist
      containers:
      - name: agnhost
        image: e2eteam/agnhost:2.26
        imagePullPolicy: IfNotPresent
        resources:
            limits:
              cpu: 10m
              memory: 50M
