apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
spec:
  replicas: {{.Replicas}}
  selector:
    matchLabels:
       feature: exec
  template:
    metadata:
       labels:
         feature: exec
    spec:
      nodeSelector: # 使用kubemark选择节点
        kubernetes.io/hostname: k8s-node1
      containers:
      - name: agnhost
        image: e2eteam/agnhost:2.26
