{{$NODES_PER_NAMESPACE := MinInt .Nodes (DefaultParam .NODES_PER_NAMESPACE 1)}}
{{$CL2_WORKLOAD_PER_NAMESPACE := DefaultParam .CL2_WORKLOAD_PER_NAMESPACE 10}}
{{$CL2_PODS_PER_WORKLOAD := DefaultParam .CL2_PODS_PER_WORKLOAD 10}}
{{$SCALED_PODS_PER_WORKLOAD := DivideInt $CL2_PODS_PER_WORKLOAD 2}}
{{$CL2_TUNINGSET_QPS := DefaultParam .CL2_TUNINGSET_QPS 10}}
{{$CL2_LISTPODS_QPS := DefaultParam .CL2_LISTPODS_QPS 3}}
{{$CL2_LISTPODS_PER_WORKLOAD := DefaultParam .CL2_LISTPODS_PER_WORKLOAD 1}}
{{$CL2_LISTPODS_IMAGE:= DefaultParam .CL2_LISTPODS_IMAGE "maclonma/pods-lister-watcher:v2"}}
{{$LISTPODS_PATALLEL_WATCH_COUNT := DefaultParam .LISTPODS_PATALLEL_WATCH_COUNT 5}}
{{$LISTPODS_LW_INTERVAL := DefaultParam .LISTPODS_LW_INTERVAL 5}}
{{$LISTPODS_WATCH_DURATION := DefaultParam .LISTPODS_WATCH_DURATION 5}}
{{$DENSITY_TEST_THROUGHPUT := DefaultParam .DENSITY_TEST_THROUGHPUT 10}}
{{$DELETE_TEST_THROUGHPUT := DefaultParam .CL2_DELETE_TEST_THROUGHPUT $DENSITY_TEST_THROUGHPUT}}
{{$RATE_LIMIT_POD_CREATION := DefaultParam .CL2_RATE_LIMIT_POD_CREATION false}}

{{$SCHEDULER_THROUGHPUT_THRESHOLD := DefaultParam .CL2_SCHEDULER_THROUGHPUT_THRESHOLD 0}}
{{$CL2_LATENCY_POD_IMAGE:= DefaultParam .CL2_LATENCY_POD_IMAGE "registry.aliyuncs.com/google_containers/pause:3.2"}}
{{$LATENCY_POD_CPU := DefaultParam .LATENCY_POD_CPU 10}}
{{$LATENCY_POD_MEMORY := DefaultParam .LATENCY_POD_MEMORY 40}}
{{$MIN_LATENCY_PODS := 3}}
{{$MIN_SATURATION_PODS_TIMEOUT := 60}}
{{$CL2_ENABLE_KUBEMARK := DefaultParam .CL2_ENABLE_KUBEMARK false}}
{{$CL2_KUBEMARK_NODE_COUNT:= DefaultParam .CL2_KUBEMARK_NODE_COUNT 1}}
{{$USE_SIMPLE_LATENCY_QUERY := DefaultParam .USE_SIMPLE_LATENCY_QUERY false}}
{{$WARM_UP_CLUSTER := DefaultParam .WARM_UP_CLUSTER true}}
{{$ENABLE_RESTART_COUNT_CHECK := DefaultParam .ENABLE_RESTART_COUNT_CHECK true}}
{{$RESTART_COUNT_THRESHOLD_OVERRIDES:= DefaultParam .RESTART_COUNT_THRESHOLD_OVERRIDES ""}}
{{$ENABLE_API_AVAILABILITY_MEASUREMENT := DefaultParam .CL2_ENABLE_API_AVAILABILITY_MEASUREMENT false}}

#Variables
{{$namespaces := DivideInt .Nodes $NODES_PER_NAMESPACE}}
{{$totalPods := MultiplyInt $namespaces $CL2_WORKLOAD_PER_NAMESPACE $CL2_PODS_PER_WORKLOAD}}
{{$saturationTime := DivideInt $totalPods $DENSITY_TEST_THROUGHPUT}}
{{$deletionTime := DivideInt $totalPods $DELETE_TEST_THROUGHPUT}}
{{$warmUpNamespaces := DivideInt $namespaces 10}}
{{$warmPodsPerNamespace := 10}}
{{$sleepDuration := "3s"}}
{{$kubemarkReplicationControllerSpec := DefaultParam .KUBEMARK_ReplicationController_SPEC "kubemark-rc.yaml"}}
{{$listpodsDeploymentSpec := DefaultParam .LISTPODS_DEPLOYMENT_SPEC "podslister-deployment.yaml"}}
{{$latencyDeploymentSpec := DefaultParam .LATENCY_DEPLOYMENT_SPEC "deployment.yaml"}}
{{$API_AVAILABILITY_PERCENTAGE_THRESHOLD := DefaultParam .CL2_API_AVAILABILITY_PERCENTAGE_THRESHOLD 99.5}}
{{$CUSTOM_ALLOWED_CONTAINER_RESTARTS := DefaultParam .CL2_CUSTOM_ALLOWED_CONTAINER_RESTARTS ""}}



name: apiserver
namespace:
  number: {{$namespaces}}
tuningSets:
- name: Sequence
  parallelismLimitedLoad:
    parallelismLimit: 1
- name: Uniform5qps
  qpsLoad:
    qps: 5
- name: default
  globalQPSLoad:
    qps: {{$CL2_TUNINGSET_QPS}}
    burst: 1
- name: RandomizedSaturationTimeLimited
  RandomizedTimeLimitedLoad:
    timeLimit: 10s
- name: RandomizedScalingTimeLimited
  RandomizedTimeLimitedLoad:
    timeLimit: 10s
- name: RandomizedDeletionTimeLimited
  RandomizedTimeLimitedLoad:
    timeLimit: 10s
- name: ListPodsQPS02
  qpsLoad:
    qps: {{$CL2_LISTPODS_QPS}}
    
    
steps:
{{if $WARM_UP_CLUSTER}}
#- name: Starting warming up pod measurements
#  measurements:
#  - Identifier: WaitForRunningWarnUpDeployments
#    Method: WaitForControlledPodsRunning
#    Params:
#      action: start
#      apiVersion: apps/v1
#      kind: Deployment
#      labelSelector: group = warmup
#      operationTimeout: 15m

- name: Creating warming up pods
  phases:
  - namespaceRange:
      min: 1
      max: {{$warmUpNamespaces}}
    replicasPerNamespace: 1
    tuningSet: default
    objectBundle:
    - basename: warmup-deployment
      objectTemplatePath: {{$latencyDeploymentSpec}}
      templateFillMap:
        Replicas: {{$warmPodsPerNamespace}}
        Group: warmup
        CpuRequest: {{$LATENCY_POD_CPU}}m
        MemoryRequest: {{$LATENCY_POD_MEMORY}}M
{{end}}

- module:
    path: /modules/measurements.yaml
    params:
      action: start

- name: Starting list/get pod measurements
  measurements:
    - Identifier: WaitForRunningListpodsDeployments
      Method: WaitForControlledPodsRunning
      Params:
        action: start
        prometheusClient: external
        apiVersion: apps/v1
        kind: Deployment
        labelSelector: group = listpods
        operationTimeout: 5m

- name: Creating list/get pods
  phases:
    - namespaceRange:
        min: 1
        max: {{$namespaces}}
      replicasPerNamespace: {{$CL2_LISTPODS_QPS}}
      tuningSet: ListPodsQPS02
      objectBundle:
        - basename: listpods-deployment
          objectTemplatePath: {{$listpodsDeploymentSpec}}
          templateFillMap:
            Replicas: {{$CL2_LISTPODS_PER_WORKLOAD}}
            Group: listpods
            Image: {{$CL2_LISTPODS_IMAGE}}
            CpuRequest: 10m
            MemoryRequest: 64M
            ParallelWatchCount: {{$LISTPODS_PATALLEL_WATCH_COUNT}}
            LwInterval: {{$LISTPODS_LW_INTERVAL}}
            WatchDuration: {{$LISTPODS_WATCH_DURATION}}

- name: Waiting for list/get pods to be running
  measurements:
    - Identifier: WaitForRunningListpodsDeployments
      Method: WaitForControlledPodsRunning
      Params:
        action: gather

- module:
    path: modules/services.yaml
    params:
      actionName: "Creating"
      namespaces: {{$namespaces}}
      servicesPerNamespace: {{DivideInt (AddInt $CL2_WORKLOAD_PER_NAMESPACE 1) 2}}

- module:
    path: /modules/configmaps-secrets.yaml
    params:
      actionName: create
      tuningSet: default
      namespaces: {{$namespaces}}
      deploymentsPerNamespace: {{$CL2_WORKLOAD_PER_NAMESPACE}}


- module:
    path: /modules/reconcile-objects.yaml
    params:
      actionName: "create"
      namespaces: {{$namespaces}}
      {{if $RATE_LIMIT_POD_CREATION}}
      tuningSet: RandomizedSaturationTimeLimited
      operationTimeout: 15m
      {{else}}
      tuningSet: default
      operationTimeout: {{AddInt $saturationTime 900}}s
      {{end}}
      deploymentSize: {{$CL2_PODS_PER_WORKLOAD}}
      deploymentsPerNamespace: {{$CL2_WORKLOAD_PER_NAMESPACE}}

{{if $ENABLE_API_AVAILABILITY_MEASUREMENT}}
- name: Unpausing APIAvailability measurement
  measurements:
  - Identifier: APIAvailability
    Method: APIAvailability
    Params:
      action: unpause
{{end}}

- module:
    path: /modules/reconcile-objects.yaml
    params:
      actionName: "scale and update"
      namespaces: {{$namespaces}}
      {{if $RATE_LIMIT_POD_CREATION}}
      tuningSet: RandomizedScalingTimeLimited
      operationTimeout: 1m
      {{else}}
      tuningSet: default
      operationTimeout: {{AddInt (DivideInt $saturationTime 4) 900}}s
      {{end}}
      deploymentSize: {{$SCALED_PODS_PER_WORKLOAD}}
      deploymentsPerNamespace: {{$CL2_WORKLOAD_PER_NAMESPACE}}

- module:
    path: /modules/reconcile-objects.yaml
    params:
      actionName: "delete"
      namespaces: {{$namespaces}}
      {{if $RATE_LIMIT_POD_CREATION}}
      tuningSet: RandomizedDeletionTimeLimited
      operationTimeout: 1m
      {{else}}
      tuningSet: default
      operationTimeout: {{AddInt $deletionTime 900}}s
      {{end}}
      deploymentSize: {{$CL2_PODS_PER_WORKLOAD}}
      deploymentsPerNamespace: 0

- module:
    path: /modules/configmaps-secrets.yaml
    params:
      actionName: delete
      tuningSet: default
      namespaces: {{$namespaces}}
      deploymentsPerNamespace: 0

- module:
    path: modules/services.yaml
    params:
      actionName: "Deleting"
      namespaces: {{$namespaces}}
      servicesPerNamespace: 0

- name: Deleting list/get pods
  phases:
    - namespaceRange:
        min: 1
        max: {{$namespaces}}
      replicasPerNamespace: 0
      tuningSet: default
      objectBundle:
        - basename: listpods-deployment
          objectTemplatePath: {{$listpodsDeploymentSpec}}

- name: Waiting for list/get pods to be deleted
  measurements:
    - Identifier: WaitForRunningListpodsDeployments
      Method: WaitForControlledPodsRunning
      Params:
        action: gather

{{if $WARM_UP_CLUSTER}}
- name: Deleting warming up pods
  phases:
    - namespaceRange:
        min: 1
        max: {{$warmUpNamespaces}}
      replicasPerNamespace: 0
      tuningSet: default
      objectBundle:
        - basename: warmup-deployment
          objectTemplatePath: {{$latencyDeploymentSpec}}
{{end}}

- module:
    path: /modules/measurements.yaml
    params:
      action: gather
